- name: Create Docker daemon configuration file
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0664

- name: Register insecure registry
  replace:
    path: /etc/docker/daemon.json
    regexp: 'REGISTRY_URL'
    replace: "docker-registry-default.{{router_host}}"

- name: Add local DNS entry for Docker registry service
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1 docker-registry-default.router.default.svc.cluster.local$'
    line: '127.0.0.1 docker-registry-default.router.default.svc.cluster.local'
  when: 'router_host == "router.default.svc.cluster.local"'

- name: Restart Docker engine
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes

- name: Prepare OpenShift home
  file: path=/usr/openshift state=directory

- name: Prepare OpenShift runtime directory
  file: path=/var/openshift state=directory

- name: Download OpenShift Origin
  get_url:
    url: https://github.com/openshift/origin/releases/download/v1.5.1/openshift-origin-server-v1.5.1-7b451fc-linux-64bit.tar.gz
    dest: /tmp/openshift-origin-server-v1.5.1-7b451fc-linux-64bit.tar.gz

- name: Unarchive downloaded OpenShift Origin archive
  unarchive:
    src: /tmp/openshift-origin-server-v1.5.1-7b451fc-linux-64bit.tar.gz
    dest: /usr/openshift
    remote_src: True
    creates: /usr/openshift/openshift-origin-server-v1.5.1-7b451fc-linux-64bit

- name: Install service systemd descriptor
  copy:
    src: openshift.service
    dest: /etc/systemd/system/openshift.service
    mode: 0664

- name: Make sure OpenShift is running
  systemd:
    name: openshift
    state: started
    enabled: yes
    daemon_reload: yes

- name: Give OpenShift time to create configuration
  pause:
    seconds: 20

- name: Flush IP tables
  command: iptables -F

- name: Make OpenShift configuration readable
  file:
    path: /openshift.local.config
    mode: u=rwX,g=rwX,o=rwX
    recurse: yes

- name: Install OpenShift client
  copy:
    remote_src: True
    src: /usr/openshift/openshift-origin-server-v1.5.1-7b451fc-linux-64bit/oc
    dest: /usr/bin/oc
    mode: 0555

- name: Install OpenShift admin client
  copy:
    remote_src: True
    src: /usr/openshift/openshift-origin-server-v1.5.1-7b451fc-linux-64bit/oadm
    dest: /usr/bin/oadm
    mode: 0555

- name: Log in as 'system:admin'
  command: /usr/bin/oc --config=/openshift.local.config/master/admin.kubeconfig login -u system:admin

- name: Add cluster read rights to 'admin' user
  command: /usr/bin/oc --config=/openshift.local.config/master/admin.kubeconfig adm policy add-cluster-role-to-user cluster-reader admin

- name: Add cluster write rights to 'admin' user
  command: /usr/bin/oc --config=/openshift.local.config/master/admin.kubeconfig adm policy add-cluster-role-to-user cluster-admin admin

- name: Log in as 'admin'
  command: oc login localhost:8443 -u admin -p admin --insecure-skip-tls-verify=true

- name: Provision integrated Docker registry
  command: /usr/bin/oadm registry --service-account=registry

- name: Add hostnetwork role to service account
  command: /usr/bin/oc adm policy add-scc-to-user hostnetwork system:serviceaccount:{{ project_name }}:router

- name: Create router
  command: /usr/bin/oc adm router

- name: Expose Docker registry service
  command: "oc expose service docker-registry --hostname=docker-registry-default.{{router_host}}"
  register: result
  failed_when: "'route \"docker-registry\" exposed' not in result.stdout and 'already exists' not in result.stderr"

- name: Add registry role to admin account
  command: /usr/bin/oadm policy add-role-to-user system:registry admin

- name: Add image-builder role to admin account
  command: /usr/bin/oadm policy add-role-to-user system:image-builder admin

- name: "Testing Docker registry access: http://docker-registry-default.{{router_host}}/v2"
  uri:
    url: "http://docker-registry-default.{{router_host}}/v2"
    status_code: 401
    return_content: yes
  register: response
  until: "'authentication required' in response.content"
  retries: 90
  delay: 1